### PR TITLE
Fix double width fonts for less common cases

### PR DESCRIPTION
**Pull request by jnjackins**
After seeing @roachsinai's issue in #43, I tried changing the width calculations to use @mattn's library. This fixes the issue and seems much simpler than trying to solve the same problem again from scratch. :)

### CODE REVIEW

**Comment by roachsinai** [comment]
Thank you! @jnjackins

**Comment by roachsinai** [comment]
Hi, @peterh does thiss pull requests have problem? Could you pls merge it?

**Comment by peterh** [comment]
> does thiss pull requests have problem?

This is the first time liner depends on any external package. It took me some time to get comfortable with the idea (plus I've been rather busy lately, and haven't had time to review the pull request details).

> Could you pls merge it?

Done. Thanks @jnjackins for the pull request.

**Comment by roachsinai** [comment]
Thanks for you work! @peterh :-)

**Pull request merged**
