### PR TITLE
Add support for Solaris

### PR DESCRIPTION
**Pull request by peterh**
Add full line editing support for Solaris. This is an updated version of the patch submitted by @ichizok in #139

### CODE REVIEW

**Comment by peterh** [comment]
@ichizok  if you could test this version on Illumos / Solaris, I would appreciate it. Thanks.

**Comment by ichizok** [comment]
I tried the example in README.md, on OpenIndiana, but didn't work well. It seems the tty settings are not proper.
I'm investigating it.

**Comment by ichizok** [comment]
Sorry for the late reply, I confirmed the latest commit https://github.com/peterh/liner/commit/58a158787cd552b11ce4a45f589a5452072c1fc0 and It seems to work OK. Thank you.

**Comment by peterh** [comment]
Thanks for testing.

**Pull request closed without merging**
