### PR TITLE
Implemented history retrieval.

### LINKED ISSUE #56: Expose history retrieval
For people using this library in CLI tools, it's always interesting to be able to *get* the history without needing to re-read the history file(s).

### PR DESCRIPTION
**Pull request by pires**
Fixes #56

### CODE REVIEW

**Comment by peterh** [comment]
Returning an internal slice is not safe, even if you take the requisite mutex.

I recommend using a bytes.Buffer with the existing WriteHistory to retrieve the current history state.

**Comment by pires** [comment]
@peterh so instead of returning `int, error` it could return `int, bytes.Buffer, error`?

**Comment by peterh** [comment]
I mean instead of adding a function to liner (which already has too many functions), you could add an example to the documentation.

So in line_test.go you could add
```go
func ExampleWriteHistory() {
   // Untested, please test and fix before submitting patch
   buf := new(bytes.Buffer)
   _, err := line.WriteHistory(buf)
   if err != nil {
      history := strings.Split(buf.String(), "\n")
      for i, line := range history {
         fmt.Println("History entry ", i, ": ", line)
      }
   }
}
```

and that example would show up in the documentation. See https://blog.golang.org/examples

**Comment by pires** [comment]
@peterh _WriteHistory_ didn't seem like the method to use but it is and it was right in my face. Thanks for doing most of the work for me. PR on the way.

**Pull request closed without merging**
